// <auto-generated />
using System;
using MatchPointBackend.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MatchPointBackend.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MatchPointBackend.Models.CommentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationPropertiesModelId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationPropertiesModelId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("MatchPointBackend.Models.CoordinatesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GeometryId")
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Coordinates");
                });

            modelBuilder.Entity("MatchPointBackend.Models.LocationCollectionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LocationCollection");
                });

            modelBuilder.Entity("MatchPointBackend.Models.LocationGeometryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CoodinatesId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CoodinatesId");

                    b.ToTable("LocationGeometry");
                });

            modelBuilder.Entity("MatchPointBackend.Models.LocationPropertiesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Conditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourtName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("CourtRating")
                        .HasColumnType("real");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<float>("SafetyRating")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("LocationPropeties");
                });

            modelBuilder.Entity("MatchPointBackend.Models.LocationsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CollectionId")
                        .HasColumnType("int");

                    b.Property<int?>("GeometryId")
                        .HasColumnType("int");

                    b.Property<int?>("LocationCollectionModelId")
                        .HasColumnType("int");

                    b.Property<int?>("PropertiesId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GeometryId");

                    b.HasIndex("LocationCollectionModelId");

                    b.HasIndex("PropertiesId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("MatchPointBackend.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MatchPointBackend.Models.CommentModel", b =>
                {
                    b.HasOne("MatchPointBackend.Models.LocationPropertiesModel", null)
                        .WithMany("Comments")
                        .HasForeignKey("LocationPropertiesModelId");
                });

            modelBuilder.Entity("MatchPointBackend.Models.LocationGeometryModel", b =>
                {
                    b.HasOne("MatchPointBackend.Models.CoordinatesModel", "Coodinates")
                        .WithMany()
                        .HasForeignKey("CoodinatesId");

                    b.Navigation("Coodinates");
                });

            modelBuilder.Entity("MatchPointBackend.Models.LocationsModel", b =>
                {
                    b.HasOne("MatchPointBackend.Models.LocationGeometryModel", "Geometry")
                        .WithMany()
                        .HasForeignKey("GeometryId");

                    b.HasOne("MatchPointBackend.Models.LocationCollectionModel", null)
                        .WithMany("Features")
                        .HasForeignKey("LocationCollectionModelId");

                    b.HasOne("MatchPointBackend.Models.LocationPropertiesModel", "Properties")
                        .WithMany()
                        .HasForeignKey("PropertiesId");

                    b.Navigation("Geometry");

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("MatchPointBackend.Models.LocationCollectionModel", b =>
                {
                    b.Navigation("Features");
                });

            modelBuilder.Entity("MatchPointBackend.Models.LocationPropertiesModel", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
